### ISSUE TITLE
Problem with Lollipop and Roboguice

### ISSUE THREAD

**Issue by CeccoCQ** [pardom-zz/ActiveAndroid#291]
Hi,
I don't know if this is the right place where I can describe my problem.
I'm using ActiveAndroid and RoboGuice together.
My app works correctly in the android OS <= 4.4.2 but when I try to execute it in the AVD 5.0 I have this error:

11-10 16:51:33.430    2108-2108/com.myproj E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process:com.myproj, PID: 2108
    java.lang.NoClassDefFoundError: roboguice.activity.SherlockAccountAuthenticatorActivity
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187)
            at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152)
            at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63)
            at com.activeandroid.Cache.initialize(Cache.java:66)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:30)
            at com.myproj.App.onCreate(App.java:36)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)

It crashes when I invoke ActiveAndroid.initialize(this) into onCreate method within my Application class.
Then I've tried to comment this line but (obviously) when I try to execute a query I've an error:

11-10 17:05:00.780    2274-2274/com.myproj E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.myproj, PID: 2274
    java.lang.RuntimeException: Unable to resume activity {com.myproj/com.myproj.ui.navigation.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.activeandroid.TableInfo com.activeandroid.ModelInfo.getTableInfo(java.lang.Class)' on a null object reference
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2951)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.activeandroid.TableInfo com.activeandroid.ModelInfo.getTableInfo(java.lang.Class)' on a null object reference
            at com.activeandroid.Cache.getTableName(Cache.java:156)
            at com.activeandroid.query.From.addFrom(From.java:169)
            at com.activeandroid.query.From.toSql(From.java:250)
            at com.activeandroid.query.From.executeSingle(From.java:311)
            at com.myproj.ui.navigation.NavigationDrawerFragment.refreshViews(NavigationDrawerFragment.java:223)
            at com.myproj.ui.navigation.NavigationDrawerFragment.onResume(NavigationDrawerFragment.java:129)
            at android.support.v4.app.Fragment.performResume(Fragment.java:1829)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:983)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
            at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1927)
            at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:444)
            at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:433)
            at android.support.v7.app.ActionBarActivity.onPostResume(ActionBarActivity.java:140)
            at android.app.Activity.performResume(Activity.java:6032)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2940)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

Please, can anyone help me?

**Comment by iTomkinas** [comment]
what I get on Lollipop without RoboGuide

``` java
11-14 17:07:05.160    2907-2907/com.sampleapp.random E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.sampleapp.random, PID: 2907
    java.lang.NoClassDefFoundError: lombok.javac.LombokOptions
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at com.activeandroid.ModelInfo.scanForModelClasses(Unknown Source)
            at com.activeandroid.ModelInfo.scanForModel(Unknown Source)
            at com.activeandroid.ModelInfo.<init>(Unknown Source)
            at com.activeandroid.Cache.initialize(Unknown Source)
            at com.activeandroid.ActiveAndroid.initialize(Unknown Source)
            at com.activeandroid.ActiveAndroid.initialize(Unknown Source)
            at com.activeandroid.ActiveAndroid.initialize(Unknown Source)
            at com.sampleapp.random.randomApplication.onCreate(randomApplication.java:33)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Edit:
I solved my problem by adding classes manually in ActiveAndroid initialization phase

``` java
    Configuration.Builder configurationBuilder = new Configuration.Builder(this);
    configurationBuilder.addModelClass(Test.class);
    configurationBuilder.addModelClass(Test2.class);
    ActiveAndroid.initialize(configurationBuilder.create());
```

**Comment by dsdebastiani** [comment]
Did you try insert `meta-data` tag in Manifest?

```
    <meta-data
        android:name="AA_MODELS"
        android:value="com.sampleapp.Test, com.sampleapp.Test2" />
```

**Comment by jagbolanos** [comment]
As an additional comment to @iTomkinas solution, that code is added to the Application, if you encounter this problem and you already had a custom Application on your project and ActiveAndroid, you will now inherit from android.app.Application instead of com.activeandroid.app.Application.

**Comment by claudiojundi** [comment]
Seriously? I need to put manually every model class?

No fix yet?

**Comment by xibaca** [comment]
I haven't noticed until just yet that this awesome library doesn't get updates since October 2014.

**Comment by abegosum** [comment]
Seeing the same issue- any word on a fix without manual configuration?

**Comment by nickserv** [comment]
I have a test suite for an application that uses an ActiveAndroid model. I keep getting the following error:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.activeandroid.TableInfo com.activeandroid.ModelInfo.getTableInfo(java.lang.Class)' on a null object reference
at com.activeandroid.Cache.getTableInfo(Cache.java:148)
at com.activeandroid.Model.<init>(Model.java:54)
at edu.rit.smoking_cessation.CheckInListItem.<init>(CheckInListItem.java:21)
at edu.rit.smoking_cessation.CheckInListItemTest.setUp(CheckInListItemTest.java:17)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
```

I have tried adding the metadata for my models, along with creating a new custom Application class that extends ActiveAndroid's class and sets up my models. Unfortunately I haven't had any luck with either. It seems like my tests will either pass or randomly fail with the error above (about 1/3 to 1/2 the times I run the tests).

Do you have any ideas? This seems to be affecting all of my Android tests (whether they are for model classes or not). Note that I am running tests on the device/emulator, and not mocking ActiveAndroid (that didn't work for me).

**Comment by Mistic92** [comment]
Models declared in manifest, lib initialized in Application class
 if (BuildConfig.DEBUG) {
                        ActiveAndroid.initialize(context, true);
                    } else {
                        ActiveAndroid.initialize(context);
                    }

```
11-20 15:39:04.660 29257-29257/com.positivegeeks.daywithscrum E/AndroidRuntime: FATAL EXCEPTION: main
11-20 15:39:04.660 29257-29257/com.positivegeeks.daywithscrum E/AndroidRuntime: Process: com.positivegeeks.daywithscrum, PID: 29257
11-20 15:39:04.660 29257-29257/com.positivegeeks.daywithscrum E/AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.positivegeeks.daywithscrum.broadcast_receivers.RandomTipsBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'com.activeandroid.TableInfo com.activeandroid.ModelInfo.getTableInfo(java.lang.Class)' on a null object reference
11-20 15:39:04.660 29257-29257/com.positivegeeks.daywithscrum E/AndroidRuntime:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2854)
11-20 15:39:04.660 29257-29257/com.positivegeeks.daywithscrum E/AndroidRuntime:     at android.app.ActivityThread.access$1700(ActivityThread.java:178)
11-20 15:39:04.660 29257-29257/com.positivegeeks.daywithscrum E/AndroidRuntime:     at...
```

**Comment by aliabbasjaffri** [comment]
Having the same issue. I tried all that is mentioned above: edited application class, the models and database meta-tags already in manifest file, but no joy! Did anyone managed to make it work?
My stacktrace:
1-23 16:14:48.738 31953-31953/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.ipal.itu.harzindagi, PID: 31953
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ipal.itu.harzindagi/com.ipal.itu.harzindagi.Activities.ChildrenListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.activeandroid.TableInfo com.activeandroid.ModelInfo.getTableInfo(java.lang.Class)' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.activeandroid.TableInfo com.activeandroid.ModelInfo.getTableInfo(java.lang.Class)' on a null object reference
                                                       at com.activeandroid.Cache.getTableInfo(Cache.java:148)
                                                       at com.activeandroid.Model.<init>(Model.java:54)
                                                       at com.ipal.itu.harzindagi.Entity.ChildInfo.<init>(ChildInfo.java:37)
                                                       at com.ipal.itu.harzindagi.Dao.ChildInfoDao.save(ChildInfoDao.java:16)
                                                       at com.ipal.itu.harzindagi.Activities.ChildrenListActivity.onCreate(ChildrenListActivity.java:32)

**Comment by kellvembarbosa** [comment]
Simple just add to AndroidManifest His "AppController" if you have not created use the ActiveAndroid "com.activeandroid.app.Application"

http://prntscr.com/9wo5jt <- custom
or
http://prntscr.com/9wo5qi <- Default activeandroid @aliabbasjaffri

**Comment by scascacha** [comment]
Same issue here, can't make it work on Lollipop smartphone. I tried every single thing above, and nothing works.

It works properly on any Android 5.1 or earlier.

**Comment by LukyanovAnatoliy** [comment]
I got rid error on Android 5.1 and higher after i changed "com.android.tools.build:gradle:2.1.0-alpha3" on "com.android.tools.build:gradle:1.5.0"

**Comment by MaximeBoure** [comment]
Thanks LukyanovAnatoliy !
Did someone manage to get ActiveAndroid compatible with gradle 2.0.0 release ?

**Comment by jlhonora** [comment]
@MaximeBoure I'm using 2.0.0 without problems, tested in 6.0, 5.1.1, 4.4.4 and others.

Here's my setup:
- Using AA's master branch (with small unrelated modifications)
- Application extends com.activeandroid.app.Application
- All models added in `meta-data`

**Comment by jlhonora** [comment]
> @scascacha: Same issue here, can't make it work on Lollipop smartphone. I tried every single thing above, and nothing works.
> It works properly on any Android 5.1 or earlier.

 I'm not sure what you mean, Android 5.1 is Lollipop...

**Comment by MaximeBoure** [comment]
@jlhonora I haven't tested on many devices 

My setup:
- Using AA's gradle com.michaelpardo:activeandroid:3.1.0-SNAPSHOT repository
- ActiveAndroid instantiated through ActiveAndroid.initialize(mContext);
- All models added in `meta-data`
- Android 5.1.1 platefrom

Updating my gradle to 2.0.0 release brought up this problem. Removing it solved it.

**Comment by jlhonora** [comment]
@MaximeBoure Are you able to use gradle 2.0.0 along with AA's master branch?

**Comment by MaximeBoure** [comment]
@jlhonora Same error with the top master branch.

**Comment by jlhonora** [comment]
I made a small sample app that seems to replicate your setup: https://github.com/jlhonora/activeandroid-example

Does it crash as well?

**Comment by cfernandomaciel** [comment]
I do get the same error. And it happens as I upgraded my android studio version, from 1.5 to 2.1.
It crashes when trying to access any model class. 
I needed to set my gradle.build to 'com.android.tools.build:gradle:2.0.0' and not let this new android studio offer me the new gradle upgrade. Then everything works. But it does not seem to be fully compatible with this new Android Studio version.

**Comment by naito77** [comment]
Hi, I used the following gradle version, but the same problem occuered when above patch of Application intitialize had done.

com.android.tools.build:gradle:2.1.0

**Comment by ton1n8o** [comment]
I've had the same problem with the following setup: 
- Android Studio 2.1
- Grade 2.1.0
- active android: 3.1.0-SNAPSHOT

But it was solved when I changed to gradle 1.5.0 or 2.0.0

**Comment by masmil1988** [comment]
Damn that day when I decided to use this library! Only a lot of problems and the developers have been abandoned...

**Comment by Artestico** [comment]
With   
- AndroidStudio 2.1 
- activeandroid:3.1.0-SNAPSHOT
- com.android.tools.build:gradle:2.1.0
- gradle/gradle-2.13

i have a crash runing the app with a message   

> Attempt to invoke virtual method 'java.lang.String com.activeandroid.TableInfo.getIdName()' on a null object reference

It's solved by coming back to :
- com.android.tools.build:gradle:2.0.0

**Comment by jlhonora** [comment]
Here's an example for AS 2.1 and gradle plugin v2.1.0: https://github.com/jlhonora/activeandroid-example

It uses:
- ActiveAndroid's master branch
- AA_MODELS specification for each model, with full package path

I'm planning on setting up a travis build so that we can have an automated way to check if things are breaking with new AS / gradle plugin versions.

**Comment by iRaam** [comment]
Just turn Instant Run off (File->Settings->Build, Execution, Deployment->Instant Run). in android Studio

http://stackoverflow.com/questions/36490573/why-active-android-is-not-working-with-gradle-2-0
