### ISSUE TITLE
Problem initializing ActiveAndroid in API 21

### ISSUE THREAD

**Issue by JesusM** [pardom-zz/ActiveAndroid#283]
When I'm trying to initialize ActiveAndroid in Android 5.0, it crashes with this error: _java.lang.NoClassDefFoundError: org.mockito.internal.runners.RunnerImpl_ . I read about this and it seems to be related with ART.

related links:
https://github.com/mockito/mockito/issues/71
https://code.google.com/p/dexmaker/issues/detail?id=39

**Comment by mpfeiffermway** [comment]
I can confirm this issue.

**Comment by roms** [comment]
I get a very similar, but not exactly the same, error on initialization:

java.lang.NoClassDefFoundError: com.google.android.gms.internal.ir
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:185)
            at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:150)
            at com.activeandroid.ModelInfo.<init>(ModelInfo.java:61)
            at com.activeandroid.Cache.initialize(Cache.java:66)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)

I'm not so sure its an ART issue as it worked on my Nexus 5 running 4.4.2 with ART. The initialization error happens on Android 5.0.

**Comment by mpfeiffermway** [comment]
After some debugging it seems that in my case ActiveAndroid chokes on a class that is included in another lib (android-logging-log4j-1.0.3.jar). It dies with a NoClassDefFoundError. As @roms mentions this only happens on Android 5.0 (emulator), not on older versions.

I've added a catch for this particular error and now it seems to work again:

```
    private void scanForModelClasses(File path, String packageName, ClassLoader classLoader) {

[...]

            try {
                Class<?> discoveredClass = Class.forName(className, false, classLoader);
                if (ReflectionUtils.isModel(discoveredClass)) {
                    @SuppressWarnings("unchecked")
                    Class<? extends Model> modelClass = (Class<? extends Model>) discoveredClass;
                    mTableInfos.put(modelClass, new TableInfo(modelClass));
                }
                else if (ReflectionUtils.isTypeSerializer(discoveredClass)) {
                    TypeSerializer instance = (TypeSerializer) discoveredClass.newInstance();
                    mTypeSerializers.put(instance.getDeserializedType(), instance);
                }
            }
/// ADDED
            catch (NoClassDefFoundError e) {
                Log.e("Couldn't find class definition.", e);
            }
/// ADDED
            catch (ClassNotFoundException e) {
                Log.e("Couldn't create class.", e);
            }
            catch (InstantiationException e) {
                Log.e("Couldn't instantiate TypeSerializer.", e);
            }
            catch (IllegalAccessException e) {
                Log.e("IllegalAccessException", e);
            }
        }
    }
```

Not sure if this is the correct solution, but it seems to work for now.

**Comment by mpfeiffermway** [comment]
Seems like there's already a pull request that should fix this: #277. And another pull request that might be of interest in this case: #247.

**Comment by mirkomane** [comment]
I get this error in Android 5 on Nexus 4 and Nexus 5:

java.lang.NoClassDefFoundError: org.codehaus.jackson.jaxrs.JacksonJsonProvider
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187)
            at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152)
            at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63)
            at com.activeandroid.Cache.initialize(Cache.java:66)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:30)
            at com.activeandroid.app.Application.onCreate(Application.java:25)

The problem seems to be that my application class extends the ActiveAndroid application class.
I solved this problem extending my application class with android.app.Application and calling a method that disables model auto searching and defines models in my Application object. Finally I call ActiveAndroid.initialize() method.

public class MyApplicationClass extends Application {
        @Override
    public void onCreate() {
              super.onCreate();
              initializeDB();
              MyDatabase.init();
    }
        /\* This method disable model auto searching defining models in the Application object. */
        protected void initializeDB() {
             Configuration.Builder configurationBuilder = new Configuration.Builder(this);
             configurationBuilder.addModelClasses(MyClassModel1.class);
             configurationBuilder.addModelClasses(MyClassModel2.class);
             configurationBuilder.addModelClasses(MyClassModel3.class);

```
         ActiveAndroid.initialize(configurationBuilder.create());
    }
```

}

**Comment by matbos** [comment]
Downloading source code and building the jar solves the problem.

**Comment by juanmacuevas** [comment]
Can I expect a release in maven repo with this issue fixed anytime soon?

**Comment by chanakin** [comment]
@mirkomane, that method doesn't disable autosearching. It still searches (I still get the crash and I am using Configuration.Builder). This might disable IF you add all the model classes in your entire project to that list, but I haven't confirmed that yet.
